#!/bin/bash
# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install basic services and applications
set -e
set -o xtrace
export DEBIAN_FRONTEND=noninteractive

# Add Openstack Kilo repo.
# Create a sources list file for Openstack Kilo.

echo "deb http://ppa.launchpad.net/ubuntu-cloud-archive/kilo-staging/ubuntu "$DISTRO_NAME" main
deb-src http://ppa.launchpad.net/ubuntu-cloud-archive/kilo-staging/ubuntu "$DISTRO_NAME" main " | sudo tee /etc/apt/sources.list.d/kilo.list

