#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
   set -x
fi

set -eu

set -o pipefail


# CONTEXT: GUEST during PRE-CONSTRUCTION as ROOT
# PURPOSE: Setup Openstack Kilo's apt-repo list so that Openstack packages can be installed.
set -e
set -o xtrace

# Add Openstack Kilo repo.
# Create a sources list file for Openstack Kilo.

echo "deb http://ppa.launchpad.net/ubuntu-cloud-archive/kilo-staging/ubuntu "$DISTRO_NAME" main
deb-src http://ppa.launchpad.net/ubuntu-cloud-archive/kilo-staging/ubuntu "$DISTRO_NAME" main " | sudo tee /etc/apt/sources.list.d/kilo.list

# Reload local package database.
apt-get update