#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Add the guest image user with shell...if the user does not already exist

set -e
set -o xtrace

TEMP_GUEST_USERNAME=${GUEST_USERNAME:-"ks"}
TEMP_GUEST_PASSWD=${GUEST_PASSWD:-"hVShbISd81CWpqWV0QWS"}

if ! id -u ${TEMP_GUEST_USERNAME} >/dev/null 2>&1; then
    echo "Adding ${TEMP_GUEST_USERNAME} user"
    useradd -G sudo -m ${TEMP_GUEST_USERNAME} -s /bin/bash
    chown ${TEMP_GUEST_USERNAME}:${TEMP_GUEST_USERNAME} /home/${TEMP_GUEST_USERNAME}
    passwd ${TEMP_GUEST_USERNAME} <<_EOF_
${TEMP_GUEST_USERNAME}
${TEMP_GUEST_PASSWD}
_EOF_
fi
